/*-
 * #%L
 * maven-execution-filter-extension
 * %%
 * Copyright (C) 2020-2021 Max Hohenegger <maven-execution-filter-extension@hohenegger.eu>
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package eu.hohenegger.filter.extension;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import org.apache.maven.building.Source;
import org.apache.maven.model.BuildBase;
import org.apache.maven.model.Model;
import org.apache.maven.model.Plugin;
import org.apache.maven.model.building.DefaultModelProcessor;
import org.apache.maven.model.building.ModelProcessor;
import org.codehaus.plexus.logging.Logger;
import org.eclipse.sisu.Typed;

/**
 * Registered under the same {@code core-default} hint - with the same {@link Typed} restriction -
 * that Maven's own {@link DefaultModelProcessor} uses, which is the canonical way for a core
 * extension to become the {@link ModelProcessor} Maven's bootstrap code actually calls (see {@code
 * org.apache.maven.cli.MavenCli#createModelProcessor}, a plain, unqualified {@code
 * container.lookup(ModelProcessor.class)}). Discovered via the {@code
 * META-INF/sisu/javax.inject.Named} index generated by the {@code sisu-maven-plugin} build plugin
 * (see pom.xml), the JSR-330 equivalent of the legacy Plexus
 * {@code @Component}/{@code @Requirement} annotations.
 *
 * <p>Claiming this hint is a hard requirement, not just a convenience: it puts this extension in
 * direct competition with any other core extension attempting the same thing (e.g.
 * maven-git-versioning-extension, which registers itself identically). Only one implementation can
 * win that lookup - which one depends on extension load order and isn't something either extension
 * fully controls - so this class also injects every other registered {@link ModelProcessor} and
 * delegates the actual disk read to one of them (see {@link #setDelegate(List)}) before filtering
 * its result. That way, whichever extension happens to win the lookup, the other still gets to run,
 * as long as it is new enough to matter here at all: maven-git-versioning-extension itself only
 * gained the equivalent "delegate to another ModelProcessor" support in 9.7.0, so with an older
 * version installed alongside this one, whichever of the two wins the lookup runs exclusively and
 * the other's logic never executes - see the "Compatibility with other core extensions" section of
 * the README.
 */
@Named("core-default")
@Typed(ModelProcessor.class)
@Singleton
public class FilteringModelProcessor extends DefaultModelProcessor {

  private static final String DEFAULT_PLUGIN_GROUP_ID = "org.apache.maven.plugins";

  private final Logger logger;
  private final PropertiesProvider propertiesProvider;

  /**
   * Accumulates results across every project's model read during a build - a reactor build reads
   * many POMs (parent aggregator plus every module), and {@link FilterInfoLifecycleParticipant}
   * needs the totals across all of them, not just whichever one happened to be read first (see
   * {@link #resetAccumulatedResults()}). Synchronized since model reading is not guaranteed to
   * happen on a single thread.
   */
  private final List<Plugin> accumulatedRemovedPlugins =
      Collections.synchronizedList(new ArrayList<>());

  private final List<Plugin> accumulatedRemainingPlugins =
      Collections.synchronizedList(new ArrayList<>());

  /**
   * The other {@link ModelProcessor} to delegate raw reading to, if any - see {@link
   * #setDelegate(List)}. {@code volatile} for safe publication: Sisu populates it, via that method,
   * once right after construction, from a thread that may differ from the ones later calling {@link
   * #read(File, Map)} and its overloads.
   */
  private volatile ModelProcessor delegate;

  /**
   * Guards against a delegation cycle: if some other extension's {@link ModelProcessor} also
   * delegates to "another" one and that chain loops back here (possible with two extensions that
   * both pick "the first other one" from a list neither fully controls the order of), this breaks
   * the cycle by falling back to {@code super.read(...)} on re-entry instead of recursing forever.
   */
  private final ThreadLocal<Boolean> readingRaw = ThreadLocal.withInitial(() -> false);

  @Inject
  public FilteringModelProcessor(Logger logger, PropertiesProvider propertiesProvider) {
    this.logger = logger;
    this.propertiesProvider = propertiesProvider;
  }

  /**
   * Sisu injects every registered {@link ModelProcessor} here, this instance included; the first
   * one that isn't this instance becomes the delegate for the actual disk read (see {@link
   * #rawRead}). Method injection rather than a constructor parameter, since a constructor
   * dependency on {@code List<ModelProcessor>} - which always includes this very instance - would
   * be a construction-order cycle Sisu cannot resolve.
   */
  @Inject
  void setDelegate(List<ModelProcessor> modelProcessors) {
    this.delegate =
        modelProcessors.stream()
            .filter(modelProcessor -> modelProcessor != this)
            .findFirst()
            .orElse(null);
  }

  private List<Plugin> parseFilteredPlugins(List<String> descriptors) {
    return descriptors.stream().map(this::loadPluginToBeFiltered).collect(Collectors.toList());
  }

  private Plugin loadPluginToBeFiltered(String pluginDescriptor) {
    var segments = pluginDescriptor.split(":");
    var plugin = new Plugin();
    plugin.setArtifactId(segments[0]);
    // Plugin's own no-arg constructor defaults groupId to "org.apache.maven.plugins" (see its
    // generated source) rather than leaving it null - harmless for a plugin actually being
    // filtered (matches() only ever reads a *filter descriptor's* groupId, never this one), but
    // it would silently defeat "no groupId means match any groupId" below if left as-is: a
    // descriptor with no groupId segment would end up looking like it specified
    // org.apache.maven.plugins after all, matching only that one groupId instead of any.
    plugin.setGroupId(segments.length > 1 ? segments[1] : null);
    if (segments.length > 2) {
      plugin.setVersion(segments[2]);
    }
    return plugin;
  }

  @Override
  public Model read(File input, Map<String, ?> options) throws IOException {
    return process(
        rawRead(
            () -> super.read(input, options),
            currentDelegate -> currentDelegate.read(input, options)),
        input.getName());
  }

  @Override
  public Model read(Reader input, Map<String, ?> options) throws IOException {
    return process(
        rawRead(
            () -> super.read(input, options),
            currentDelegate -> currentDelegate.read(input, options)),
        locationOf(options));
  }

  @Override
  public Model read(InputStream input, Map<String, ?> options) throws IOException {
    return process(
        rawRead(
            () -> super.read(input, options),
            currentDelegate -> currentDelegate.read(input, options)),
        locationOf(options));
  }

  /**
   * Reads the raw model via {@link #delegate} when one is present (see {@link #setDelegate(List)})
   * so that another core extension's own model processing - e.g. maven-git-versioning-extension
   * rewriting the version - still runs, rather than being skipped in favor of Maven's plain,
   * unmodified {@code super.read(...)}. Falls back to {@code viaSuper} when there is no delegate
   * (the common case: this extension used alone) or on re-entry (see {@link #readingRaw}).
   */
  private Model rawRead(IoSupplier<Model> viaSuper, IoFunction<ModelProcessor, Model> viaDelegate)
      throws IOException {
    var currentDelegate = delegate;
    if (currentDelegate == null || readingRaw.get()) {
      return viaSuper.get();
    }
    readingRaw.set(true);
    try {
      return viaDelegate.apply(currentDelegate);
    } finally {
      readingRaw.set(false);
    }
  }

  @FunctionalInterface
  private interface IoSupplier<T> {
    T get() throws IOException;
  }

  @FunctionalInterface
  private interface IoFunction<T, R> {
    R apply(T t) throws IOException;
  }

  private Model process(Model model, String location) throws IOException {
    if (isProjectPom(location)) {
      filter(model);
    }
    return model.clone();
  }

  private static String locationOf(Map<String, ?> options) {
    var source = options == null ? null : options.get(ModelProcessor.SOURCE);
    return source instanceof Source ? ((Source) source).getLocation() : null;
  }

  /**
   * Distinguishes an actual project/parent POM (always named {@code pom.xml} on disk) from a POM
   * that Maven reads merely to resolve an artifact's metadata (dependency, plugin, extension, ...),
   * which is cached in the local repository under {@code <artifactId>-<version>.pom}. Without this
   * check, plugins would be "filtered" (and logged) out of unrelated third-party POMs read only for
   * dependency resolution, which has no effect on the actual build but produces confusing log noise
   * - exactly what this extension is meant to avoid. When the location cannot be determined,
   * filtering is skipped: empirically, that happens for artifact-metadata reads (e.g. resolving
   * this extension's own dependency chain, including Maven's/ASF's own parent POMs, which commonly
   * declare source/javadoc/deploy plugin configuration for their own release process) rather than
   * for the actual project POM, whose {@code read(File, ...)} overload always has a real filename.
   */
  private static boolean isProjectPom(String location) {
    if (location == null) {
      return false;
    }
    var normalized = location.replace('\\', '/');
    var lastSlash = normalized.lastIndexOf('/');
    var fileName = lastSlash >= 0 ? normalized.substring(lastSlash + 1) : normalized;
    return "pom.xml".equals(fileName);
  }

  Model filter(Model model) {
    var configuredDescriptors = propertiesProvider.getPluginDescriptors();
    var filteredPlugins = parseFilteredPlugins(configuredDescriptors);

    var removedPlugins = new ArrayList<Plugin>();
    var remainingPlugins = new ArrayList<Plugin>();
    if (!filteredPlugins.isEmpty()) {
      logger.debug("filtering: " + model);
      filterBuild(model.getBuild(), filteredPlugins, removedPlugins, remainingPlugins);
      model
          .getProfiles()
          .forEach(
              profile ->
                  filterBuild(
                      profile.getBuild(), filteredPlugins, removedPlugins, remainingPlugins));
    }

    accumulatedRemovedPlugins.addAll(removedPlugins);
    accumulatedRemainingPlugins.addAll(remainingPlugins);

    return model;
  }

  /**
   * Clears the results accumulated so far - called once per build (from {@link
   * FilterInfoLifecycleParticipant#afterSessionStart}, which fires before any project is read),
   * since this component is a singleton reused across builds under a Maven daemon (mvnd) and would
   * otherwise keep reporting totals from previous builds too.
   */
  void resetAccumulatedResults() {
    accumulatedRemovedPlugins.clear();
    accumulatedRemainingPlugins.clear();
  }

  List<Plugin> accumulatedRemovedPlugins() {
    return List.copyOf(accumulatedRemovedPlugins);
  }

  List<Plugin> accumulatedRemainingPlugins() {
    return List.copyOf(accumulatedRemainingPlugins);
  }

  private void filterBuild(
      BuildBase build, List<Plugin> filteredPlugins, List<Plugin> removed, List<Plugin> remaining) {
    if (build == null) {
      return;
    }
    var partitioned =
        build.getPlugins().stream()
            .collect(
                Collectors.partitioningBy(plugin -> isFilteredPlugin(plugin, filteredPlugins)));
    build.setPlugins(partitioned.get(false));
    removed.addAll(partitioned.get(true));
    remaining.addAll(partitioned.get(false));
  }

  boolean isFilteredPlugin(Plugin plugin, List<Plugin> filteredPlugins) {
    var ofilteredPlugin =
        filteredPlugins.stream()
            .filter(filteredPlugin -> matches(plugin, filteredPlugin))
            .findFirst();

    if (ofilteredPlugin.isPresent()) {
      logger.info(
          String.format(
              "Plugin [%s:%s:%s] filtered",
              plugin.getGroupId(), plugin.getArtifactId(), plugin.getVersion()));
    }

    return ofilteredPlugin.isPresent();
  }

  /**
   * A plugin matches a filter descriptor if the artifactId is equal, and the groupId/version are
   * either equal or left unspecified (null) in the filter descriptor. Plugin declarations omitting
   * the groupId (legal for core plugins) are compared as if they had Maven's default {@value
   * #DEFAULT_PLUGIN_GROUP_ID}, since that default is only applied later on, during model
   * inheritance/normalization.
   */
  private boolean matches(Plugin plugin, Plugin filteredPlugin) {
    if (!Objects.equals(plugin.getArtifactId(), filteredPlugin.getArtifactId())) {
      return false;
    }
    if (filteredPlugin.getGroupId() != null
        && !filteredPlugin.getGroupId().equals(effectiveGroupId(plugin))) {
      return false;
    }
    return filteredPlugin.getVersion() == null
        || filteredPlugin.getVersion().equals(plugin.getVersion());
  }

  private String effectiveGroupId(Plugin plugin) {
    return plugin.getGroupId() != null ? plugin.getGroupId() : DEFAULT_PLUGIN_GROUP_ID;
  }
}
