/*-
 * #%L
 * maven-execution-filter-extension
 * %%
 * Copyright (C) 2020-2021 Max Hohenegger <maven-execution-filter-extension@hohenegger.eu>
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package eu.hohenegger.filter.extension;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import org.apache.maven.building.Source;
import org.apache.maven.model.BuildBase;
import org.apache.maven.model.Model;
import org.apache.maven.model.Plugin;
import org.apache.maven.model.building.DefaultModelProcessor;
import org.apache.maven.model.building.ModelProcessor;
import org.codehaus.plexus.logging.Logger;

/**
 * Registered under a hint other than Maven's own {@code core-default} for {@link ModelProcessor},
 * which is the convention Maven's DI container (Eclipse Sisu) uses to let a differently-hinted
 * implementation take over an unqualified {@code ModelProcessor} lookup - see {@code
 * org.apache.maven.model.building.DefaultModelProcessor} and its usage in maven-core's own {@code
 * META-INF/plexus/components.xml}. Discovered via the {@code META-INF/sisu/javax.inject.Named}
 * index generated by the {@code sisu-maven-plugin} build plugin (see pom.xml), the JSR-330
 * equivalent of the legacy Plexus {@code @Component}/{@code @Requirement} annotations.
 */
@Named("filtering-model-reader")
@Singleton
public class FilteringModelProcessor extends DefaultModelProcessor {

  private static final String DEFAULT_PLUGIN_GROUP_ID = "org.apache.maven.plugins";

  private final Logger logger;
  private final PropertiesProvider propertiesProvider;

  /**
   * Accumulates results across every project's model read during a build - a reactor build reads
   * many POMs (parent aggregator plus every module), and {@link FilterInfoLifecycleParticipant}
   * needs the totals across all of them, not just whichever one happened to be read first (see
   * {@link #resetAccumulatedResults()}). Synchronized since model reading is not guaranteed to
   * happen on a single thread.
   */
  private final List<Plugin> accumulatedRemovedPlugins =
      Collections.synchronizedList(new ArrayList<>());

  private final List<Plugin> accumulatedRemainingPlugins =
      Collections.synchronizedList(new ArrayList<>());

  @Inject
  public FilteringModelProcessor(Logger logger, PropertiesProvider propertiesProvider) {
    this.logger = logger;
    this.propertiesProvider = propertiesProvider;
  }

  private List<Plugin> parseFilteredPlugins(List<String> descriptors) {
    return descriptors.stream().map(this::loadPluginToBeFiltered).toList();
  }

  private Plugin loadPluginToBeFiltered(String pluginDescriptor) {
    var segments = pluginDescriptor.split(":");
    var plugin = new Plugin();
    plugin.setArtifactId(segments[0]);
    if (segments.length > 1) {
      plugin.setGroupId(segments[1]);
    }
    if (segments.length > 2) {
      plugin.setVersion(segments[2]);
    }
    return plugin;
  }

  @Override
  public Model read(File input, Map<String, ?> options) throws IOException {
    return process(super.read(input, options), input.getName());
  }

  @Override
  public Model read(Reader input, Map<String, ?> options) throws IOException {
    return process(super.read(input, options), locationOf(options));
  }

  @Override
  public Model read(InputStream input, Map<String, ?> options) throws IOException {
    return process(super.read(input, options), locationOf(options));
  }

  private Model process(Model model, String location) throws IOException {
    if (isProjectPom(location)) {
      filter(model);
    }
    return model.clone();
  }

  private static String locationOf(Map<String, ?> options) {
    var source = options == null ? null : options.get(ModelProcessor.SOURCE);
    return source instanceof Source theSource ? theSource.getLocation() : null;
  }

  /**
   * Distinguishes an actual project/parent POM (always named {@code pom.xml} on disk) from a POM
   * that Maven reads merely to resolve an artifact's metadata (dependency, plugin, extension, ...),
   * which is cached in the local repository under {@code <artifactId>-<version>.pom}. Without this
   * check, plugins would be "filtered" (and logged) out of unrelated third-party POMs read only for
   * dependency resolution, which has no effect on the actual build but produces confusing log noise
   * - exactly what this extension is meant to avoid. When the location cannot be determined,
   * filtering is skipped: empirically, that happens for artifact-metadata reads (e.g. resolving
   * this extension's own dependency chain, including Maven's/ASF's own parent POMs, which commonly
   * declare source/javadoc/deploy plugin configuration for their own release process) rather than
   * for the actual project POM, whose {@code read(File, ...)} overload always has a real filename.
   */
  private static boolean isProjectPom(String location) {
    if (location == null) {
      return false;
    }
    var normalized = location.replace('\\', '/');
    var lastSlash = normalized.lastIndexOf('/');
    var fileName = lastSlash >= 0 ? normalized.substring(lastSlash + 1) : normalized;
    return "pom.xml".equals(fileName);
  }

  Model filter(Model model) {
    var configuredDescriptors = propertiesProvider.getPluginDescriptors();
    var filteredPlugins = parseFilteredPlugins(configuredDescriptors);

    var removedPlugins = new ArrayList<Plugin>();
    var remainingPlugins = new ArrayList<Plugin>();
    if (!filteredPlugins.isEmpty()) {
      logger.debug("filtering: " + model);
      filterBuild(model.getBuild(), filteredPlugins, removedPlugins, remainingPlugins);
      model
          .getProfiles()
          .forEach(
              profile ->
                  filterBuild(
                      profile.getBuild(), filteredPlugins, removedPlugins, remainingPlugins));
    }

    accumulatedRemovedPlugins.addAll(removedPlugins);
    accumulatedRemainingPlugins.addAll(remainingPlugins);

    return model;
  }

  /**
   * Clears the results accumulated so far - called once per build (from {@link
   * FilterInfoLifecycleParticipant#afterSessionStart}, which fires before any project is read),
   * since this component is a singleton reused across builds under a Maven daemon (mvnd) and would
   * otherwise keep reporting totals from previous builds too.
   */
  void resetAccumulatedResults() {
    accumulatedRemovedPlugins.clear();
    accumulatedRemainingPlugins.clear();
  }

  List<Plugin> accumulatedRemovedPlugins() {
    return List.copyOf(accumulatedRemovedPlugins);
  }

  List<Plugin> accumulatedRemainingPlugins() {
    return List.copyOf(accumulatedRemainingPlugins);
  }

  private void filterBuild(
      BuildBase build, List<Plugin> filteredPlugins, List<Plugin> removed, List<Plugin> remaining) {
    if (build == null) {
      return;
    }
    var partitioned =
        build.getPlugins().stream()
            .collect(
                Collectors.partitioningBy(plugin -> isFilteredPlugin(plugin, filteredPlugins)));
    build.setPlugins(partitioned.get(false));
    removed.addAll(partitioned.get(true));
    remaining.addAll(partitioned.get(false));
  }

  boolean isFilteredPlugin(Plugin plugin, List<Plugin> filteredPlugins) {
    var ofilteredPlugin =
        filteredPlugins.stream()
            .filter(filteredPlugin -> matches(plugin, filteredPlugin))
            .findFirst();

    if (ofilteredPlugin.isPresent()) {
      logger.info(
          "Plugin [%s:%s:%s] filtered"
              .formatted(plugin.getGroupId(), plugin.getArtifactId(), plugin.getVersion()));
    }

    return ofilteredPlugin.isPresent();
  }

  /**
   * A plugin matches a filter descriptor if the artifactId is equal, and the groupId/version are
   * either equal or left unspecified (null) in the filter descriptor. Plugin declarations omitting
   * the groupId (legal for core plugins) are compared as if they had Maven's default {@value
   * #DEFAULT_PLUGIN_GROUP_ID}, since that default is only applied later on, during model
   * inheritance/normalization.
   */
  private boolean matches(Plugin plugin, Plugin filteredPlugin) {
    if (!Objects.equals(plugin.getArtifactId(), filteredPlugin.getArtifactId())) {
      return false;
    }
    if (filteredPlugin.getGroupId() != null
        && !filteredPlugin.getGroupId().equals(effectiveGroupId(plugin))) {
      return false;
    }
    return filteredPlugin.getVersion() == null
        || filteredPlugin.getVersion().equals(plugin.getVersion());
  }

  private String effectiveGroupId(Plugin plugin) {
    return plugin.getGroupId() != null ? plugin.getGroupId() : DEFAULT_PLUGIN_GROUP_ID;
  }
}
